"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Constants = void 0;
var Constants;
(function (Constants) {
    Constants["MSG_TYPES_START_GAME"] = "start_game";
    Constants["MSG_TYPES_JOIN_GAME"] = "join_game";
    Constants["MSG_TYPES_GAME_UPDATE"] = "update_game";
    Constants["MSG_TYPES_INPUT"] = "input";
    Constants["MSG_TYPES_GAME_OVER"] = "dead";
    Constants["JOIN_ROOM"] = "join_room";
    Constants["JOIN_ROOM_SUCCESS"] = "join_room_suc";
    Constants["JOIN_ROOM_FAIL"] = "join_room_fail";
    Constants["CREATE_ROOM"] = "create_room";
    Constants["ROOM_CREATED"] = "room_created";
    Constants["LEAVE_ROOM"] = "leave_room";
    Constants["LEAVE_ROOM_SUCCESS"] = "leave_room_suc";
    Constants["ROOM_WAITING_PLAYERS_RESPONSE"] = "room_waiting_players_response";
    Constants["LEVER_IS_TOUCHED"] = "lever_is_touched";
    Constants["GET_PLAYER_STATS"] = "get_player_stats";
    Constants["CREATE_USERNAME"] = "create_username";
    Constants["PLAYER_DISCONNECT"] = "player_disconnect";
})(Constants = exports.Constants || (exports.Constants = {}));
